const { callAgent } = require("../config/groqClient");
const { safeParseJSON } = require("../utils/jsonParser");

const REVIEW_PROMPT = `You are the Self-Review Agent in CogniCraft. You review code that was JUST generated by another agent,
looking for bugs, missed edge cases, and correctness issues. Be critical but fair.

Check ALL of the following categories explicitly before deciding hasIssues:
1. COMPILE/PARSE CORRECTNESS: For compiled languages (C++, Java, C, etc.), verify every function is
   declared (prototype or full definition) BEFORE it is first called/used in the file. A function defined
   only later in the file, but called earlier, is a compile error (forward-declaration issue) — flag it
   explicitly if found. Verify all necessary #include/import statements are present for every standard
   function used (e.g. std::max, std::min, algorithm header, etc.).
2. LOGICAL CORRECTNESS: trace through at least one non-trivial example by hand mentally and check the
   algorithm actually produces the right answer.
3. EDGE CASES: empty input, single element, all-equal elements, size-mismatched inputs, boundary indices.
4. RUNTIME SAFETY: out-of-bounds access, null/empty dereferences, off-by-one errors.

Respond ONLY with valid JSON, no markdown fences:
{
  "hasIssues": boolean,
  "issues": ["issue 1", "issue 2"],
  "reasoning": "summary of your review findings, explicitly mention which categories above you checked",
  "confidence": number (0-100)
}`;

const REFINE_PROMPT = `You are the Refiner Agent in CogniCraft. You receive code and a list of issues found by the Self-Review Agent.
Fix ALL listed issues and return the corrected, complete code.

Respond ONLY with valid JSON, no markdown fences:
{
  "code": "the corrected complete code, with \\n for newlines",
  "fixesApplied": ["fix 1 description", "fix 2 description"],
  "reasoning": "brief summary of what changed and why",
  "confidence": number (0-100)
}`;

async function runSelfReview(code, language, reporter) {
  reporter.started("reviewer_self", "Self-Review Agent", "Checking generated code for issues...");

  const result = await callAgent({
    systemPrompt: REVIEW_PROMPT,
    userPrompt: `Language: ${language}\n\nCode:\n${code}`,
    temperature: 0.2,
    jsonMode: true,
  });

  if (!result.success) {
    reporter.failed("reviewer_self", "Self-Review Agent", "Review failed, skipping refinement");
    return { hasIssues: false, issues: [], reasoning: "Review skipped", confidence: 50 };
  }

  const review = safeParseJSON(result.content, {
    hasIssues: false,
    issues: [],
    reasoning: "No issues detected",
    confidence: 60,
  });

  reporter.completed("reviewer_self", "Self-Review Agent", {
    message: review.hasIssues
      ? `Found ${review.issues.length} issue(s) — sending to Refiner`
      : "No issues found, code looks good",
    reasoning: review.reasoning,
    confidence: review.confidence,
    data: review,
  });

  return review;
}

async function runRefiner(code, language, issues, reporter) {
  reporter.started("refiner", "Refiner Agent", "Auto-fixing identified issues...");

  const userPrompt = `Language: ${language}\n\nOriginal code:\n${code}\n\nIssues to fix:\n${issues
    .map((i, idx) => `${idx + 1}. ${i}`)
    .join("\n")}`;

  const result = await callAgent({
    systemPrompt: REFINE_PROMPT,
    userPrompt,
    temperature: 0.2,
    jsonMode: true,
  });

  if (!result.success) {
    reporter.failed("refiner", "Refiner Agent", "Refinement failed, using original code");
    return { code, fixesApplied: [], reasoning: "Refinement skipped", confidence: 50 };
  }

  const refined = safeParseJSON(result.content, {
    code,
    fixesApplied: [],
    reasoning: "Refinement parsing failed, original code retained",
    confidence: 50,
  });

  reporter.completed("refiner", "Refiner Agent", {
    message: `Applied ${refined.fixesApplied.length} fix(es)`,
    reasoning: refined.reasoning,
    confidence: refined.confidence,
    data: refined,
  });

  return refined;
}

module.exports = { runSelfReview, runRefiner };
